### ISSUE TITLE
Think of a way to merge the `core` and `periphery` dirs

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/deployments#10]
Ref https://github.com/sablier-labs/v2-core/pull/979

**Comment by andreivladbrg** [comment]
Idea:
```tree
└── deployments
    ├── lockup
    │  ├── v1.0.0 // both core and periphery
    │  └── v1.1.0 // both core and periphery 
    └── flow
       ├── v1.0.0 
       └── v1.1.0 
```

**Comment by smol-ninja** [comment]
Looks good to me.

**Comment by PaulRBerg** [comment]
Wouldn't it be better to rename `periphery` to `airdrops`, and add a warning in <v1.2.0 that the npm package hsed to be called `@sablier/v2-periphery`?

**Comment by andreivladbrg** [comment]
this issue was created in august, at that time there was no discussion about `airdrop` repo (will update the OP)

**Comment by PaulRBerg** [comment]
OK, so you agree with my proposal?

**Comment by andreivladbrg** [comment]
> Wouldn't it be better to rename periphery to airdrops, and add a warning in <v1.2.0 that the npm package hsed to be called @sablier/v2-periphery?

@PaulRBerg  just realized that this wouldn’t work, as the `periphery` used to contain the proxy contract in the earlier versions. so, IMO naming it “airdrops” would be misleading. wdyt?

we will have `airdrops` only for the new versions, and we can mention “previously known as periphery.”

**Comment by andreivladbrg** [comment]
> 
How about moving previously deployed merkle campaign contracts to airdrops and keep rest (batch, proxy) etc in core?

even more confusing IMO :))

<img width="350" alt="image" src="https://github.com/user-attachments/assets/7e3bf464-9b50-4106-a101-fa4f747cabef">

**Comment by PaulRBerg** [comment]
good point @andreivladbrg

> we will have `airdrops` only for the new versions, and we can mention “previously known as periphery.”

Sounds good
